name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.16'
          - '5.18'
          - '5.20'
          - '5.22'
          - '5.30'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Fix ExtUtils::MakeMaker (for Perl 5.16 and 5.18)
        run: cpanm -n App::cpanminus ExtUtils::MakeMaker
      - name: Install dependencies
        run: cpanm -n -q --installdeps .
      - name: Run tests
        run: prove -l t
      - name: Coverage
        if: ${{ matrix.perl-version == '5.30' }}
        run: |
          cpanm -n -q --with-develop --installdeps .
          perl Makefile.PL
          cover -test -report coveralls
          cover -report kritika
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          KRITIKA_TOKEN: ${{ secrets.KRITIKA_TOKEN }}
          CI_BUILD_REF: ${{ github.sha }}
